- name: Checkout
  uses: QAInsights/PerfAction@v3.1
  with:
    test-plan-path: /Ingenio/media-jmeter-astrologydotcom/IngenioJmeterScripts/Sunsigns/Sunsign_Testplans/SunsignsHomepage.jmx
    args: ''
    - name: Upload Results
  uses: actions/upload-artifact@v2
  with:
    name: jmeter-results
    path: result.jtl
